FROM python:3.11.9-slim-bullseye

ENV PIP_DISABLE_VERSION-CHECK 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /code

# COPY ./../user_management/requirements.txt .
# RUN pip install -r requirements.txt

# COPY . .

# RUN sleep 8000

# https://learndjango.com/tutorials/django-docker-and-postgresql-tutorial
