services:
  web:
    build: ./app
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    restart: on-failure
    depends_on:
      - db
  db:
    image: postgres:16-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    restart: on-failure
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}

volumes:
    postgres_data: