services:
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - web
    restart: on-failure

  web:
    build: ./web
    command:
      - sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic && gunicorn user_stats.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    restart: on-failure

volumes:
  postgres_data:
  static_volume:
  media_volume: